[package]
name = "log_maintenance"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]
repo = "https://github.com/FreeMasen/log_maintenance"

[dependencies]
walkdir = "2.2.5"
dirs = "1.0.3"